version: '3'

services:
  api: # Node.js App
    container_name: gs-api
    build: server
    ports:
      - "3000:3000" # Expose API port
    environment:
      - HOST=gs-search
    volumes: # Attach local book data directory
      - ./server/books:/usr/src/server/books

  frontend: # Server For Frontend App
    container_name: gs-frontend
    build: angular-frontend
    ports:
      - "8000:80" # Forward site to localhost:4200
    depends_on:
      - api

  elasticsearch: # Elasticsearch Instance
    container_name: gs-search
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    volumes: # Persist ES data in seperate "esdata" volume
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports: # Expose ElasticSearch ports
      - "9300:9300"
      - "9200:9200"

volumes:
  esdata: